# Generated by Django 4.0.3 on 2022-03-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ugency_level',
            new_name='urgency_level',
        ),
    ]
