# Generated by Django 3.0.7 on 2022-03-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220324_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='urgency_level',
            field=models.CharField(choices=[('0', 'low'), ('1', 'normal'), ('2', 'High'), ('3', 'Critical')], default='low', max_length=10),
        ),
    ]
