# Generated by Django 3.0.7 on 2022-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220325_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='task',
        ),
    ]
