# Generated by Django 3.0.7 on 2022-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220328_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='urgency_level',
        ),
    ]
